apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - _namespace.yaml
  - cert-manager.yaml
  - leane-dev-cert.yaml
  - prod-issuer.yaml
  - repos/jetstack.yaml
  - self-issuer.yaml
  - staging-issuer.yaml
