apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocket-id
resources:
  - _namespace.yaml
  - hr.yaml
secretGenerator:
  - name: pocket-id-env
    envs:
      - secrets.enc.env
components:
  - ../common
configurations:
  - kustomizeconfig.yaml
