apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imagestore
  namespace: imagestore
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "internal"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: im.sko.ai
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              name: http
        path: /(.*)
        pathType: Prefix
      - backend:
          service:
            name: backend
            port:
              name: http
        path: /api/(.*)
        pathType: Prefix
  tls:
  - hosts:
    - im.sko.ai
    secretName: ingress-cert-im
