---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: imagestore
resources:
  - _namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - postgres.yaml
  - imagestore-pvc.yaml
