---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: prometheus
    namespace: flux-system
  - kind: Deployment
    name: grafana
    namespace: flux-system
  interval: 1h0m0s
  path: ./manifests/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
  timeout: 2m0s

