apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authelia
- automation
- cert-manager
- default
#- elastic
- flux-system
- gitea
#- harbor
- ingress-nginx
- kube-system
- mail
- media
- ngircd
- synology-csi
- torrent
- vaultwarden
# Need amd64
- renovate
- gitlab
- kasten-io
- logging
#- monitoring
