apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - automation
  - cert-manager
  - code-server
  - default
  - envoy
  - flux-system
  - gitlab
  - haproxy
  - headlamp
  - immich
  - k8s-gateway
  - agentgateway
  - kube-flannel
  - kube-system
  - logging
  - mail
  - media
  - minilb
  - nfs-subdir
  - pocket-id
  - rbac
  - renovate
  - synology-csi
  - vaultwarden
  - victoria-metrics
