apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drone
resources:
- _namespace.yaml
- buildkit
- drone-charts.yaml
- drone-runner.yaml
- drone-secrets.yaml
- drone.yaml
- limit-range.yaml
