apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap
  namespace: wireguard
data:
  SERVERURL: "wg.sko.ai"
  SERVERPORT: "51820"
  PEERS: "2"
  ALLOWEDIPS: "0.0.0.0/0, ::/0"
  INTERNAL_SUBNET: "192.168.7.0"
