---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thelounge
  namespace: default
  annotations:
    kubernetes.io/ingress.class: internal
spec:
  rules:
    - host: irc.sko.ai
      http:
        paths:
          - backend:
              service:
                name: thelounge
                port:
                  number: 9090
            path: /
            pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: thelounge
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: thelounge
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thelounge
  namespace: default
spec:
  selector:
    matchLabels:
      app: thelounge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: thelounge
    spec:
      containers:
        - image: ghcr.io/linuxserver/thelounge:version-4.3.0
          name: thelounge
          env:
          ports:
            - containerPort: 9000
              name: thelounge
          volumeMounts:
            - name: pv-thelounge
              mountPath: /config
      volumes:
        - name: pv-thelounge
          persistentVolumeClaim:
            claimName: thelounge-v3
