apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy
resources:
  - _namespace.yaml
  - gateways
  - hr.yaml
  - proxy.yaml
  - security
  - ../netpols/allow-all-ingress
components:
  - ../common
