- Cloud:
    - Synology Photos:
        icon: synology-photos
        href: https://syno/photos/
        description: Photo storage and viewer
    - Synology Drive:
        icon: synology-drive
        href: https://syno/drive/
        description: Create, share and access documents from anywhere
- Media:
    - Flood WebUI:
        icon: flood
        href: https://fl.sko.ai/
        description: Beautiful WebUI for torrent clients
    - qBittorrent:
        icon: qbittorrent
        href: http://syno.sko.ai:55555/
        description: Torrent client
