apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
resources:
  - _namespace.yaml
  - deploy.yaml
  - secret.yaml
labels:
  - pairs:
      app.kubernetes.io/name: cloudflared
    includeSelectors: true
components:
  - ../common
