---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
      version: 4.2.0
  interval: 1h
  values:
    controller:
      replicaCount: 2
      containerPort:
        http: 9080
        https: 9443
      service:
        type: NodePort
        externalIPs:
          - ${EI_INGRESS_EX}
        externalTrafficPolicy: Local
      ingressClass: external
      ingressClassResource:
        name: external
        enabled: true
        default: false
        controllerValue: "k8s.io/external-ingress-nginx"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - ingress-nginx-external
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - controller
                topologyKey: kubernetes.io/hostname
      config:
        proxy-body-size: '0'
        ssl-protocols: TLSv1.3 TLSv1.2
        # Helps prevent auth loops
        force-ssl-redirect: true
        global-auth-url: https://gate.sko.ai/api/verify
        global-auth-signin: https://gate.sko.ai
        hsts: false
        location-snippet: |
          add_header X-Frame-Options SAMEORIGIN always;
          add_header X-Content-Type-Options nosniff always;
          add_header X-XSS-Protection "1; mode=block" always;
      extraArgs:
        http-port: 9080
        https-port: 9443
        default-ssl-certificate: cert-manager/sko-ai-tls
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 500Mi
    defaultBackend:
      enabled: false
