apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hr.yaml
configMapGenerator:
  - name: echo-conf
    files:
      - config/nginx.conf
configurations:
  - kustomizeconfig.yaml
