apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - baikal
  - blog
  - cyberchef
  - dogcalc
  - echo
  - hass
  - homepage
  - kromgo
  - leane-dev
  - mealie
  - net-tools
  - omada
  - reminders
  - scanner
  - syno
  - thelounge
  - vikunja
  - regcred.enc.yaml
components:
  - ../common
