apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - _namespace.yaml
  - autobrr
  - calibre
  - calibre-web
  - flood
  - jellyfin
  - lidarr
  - prowlarr
  - qbit_manage
  - radarr
  - recyclarr
  - seerr
  - sonarr
  - torrents-pv-v2.yaml
  - torrents-pvc-v2.yaml
components:
  - ../common
