apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
- _namespace.yaml
- autobrr
- bazarr
- blackcandy
- calibre
- calibre-web
- flood
- jellyfin
- jellyseerr
- prowlarr
- qbit_manage
- radarr
- lidarr
- readarr
- recyclarr
- sonarr
- torrents-pv-v2.yaml
- torrents-pvc-v2.yaml
components:
- ../common
