apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir
  namespace: flux-system
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  timeout: 3m
